### ISSUE TITLE
Not catching certian errors

### ISSUE THREAD

**Issue by codejamninja** [RyanZim/EJS-Lint#44] opened 2018-10-13 16:24 UTC
ejs-lint does not recognize the following as an error, but ejs throws an error.

Any reason why ejs-lint doesn't think that is a problem?

```ejs
<% hello =>
```

**Comment by RyanZim** [comment] 2018-10-15 15:22
EJS-Lint only catches errors in your JS inside your valid script tags. PR welcome to expand it to catch more. Closing since this a basically a dupe of https://github.com/RyanZim/EJS-Lint/issues/32.

**Closed by RyanZim** 2018-10-15 15:22 UTC

**Comment by codejamninja** [comment] 2018-10-15 23:36
Ah, thanks
